### PR TITLE
Fix sequrity allerts

### PR DESCRIPTION
**Pull request by JoranAngevaare**
We should address these kind of alerts,
afbeelding

I'm not sure if this:
1. Will break anything
2. Affects working code (I'm not even sure if the XOM runs somewhere)

For more info, please checkout:
https://github.com/XENONnT/xom/security/dependabot

### CODE REVIEW

**Comment by lucascottolavina** [comment]
Hi Joran, thanks for having a look at it! However, everything is inside the folder xom is deprecated. In particular, starting from the main folder we have four subfolders:

- backend (the official backend, Laura and myself have completely rewritten it in order to work with strax and have uniquely python code, since Lotfi was using a mixture of bash and python)
- frontend (the official frontend, it's always online and used for testing) 
- utils (utilities to test the xom database)
- xom (this is the old package originally written by Lotfi, we are temporary keeping it but all its content can be deleted)

The changes you are proposing is in the xom directory. The modification makes sense and I thank you but it affects only the deprecated part. Indeed it is time to completely get rid of it to avoid confusion.

**Comment by lucascottolavina** [comment]
If you don't mind, I will use this PR to remove the whole xom directory, then I merge it

**Comment by JoranAngevaare** [comment]
Sounds good Luca, I just got an alarming notification from github so took some action. Great that you take over 😄

**Comment by JoranAngevaare** [comment]
@lucascottolavina , I'm closing this PR please reopen if it would still have some use

**Pull request closed without merging**
